### ISSUE TITLE
how to keep in sync efficiently

### ISSUE THREAD

**Issue by geoHeil** [conda-forge/dagster-feedstock#356]
### Comment:

see https://github.com/conda-forge/dagster-feedstock/issues/353

I now have:

- https://github.com/conda-forge/dagster-cloud-cli-feedstock/pull/1
- https://github.com/conda-forge/dagster-cloud-feedstock/pull/1

they need dagster`s new release to build i.e. have a dependency on this one here.

Is there any sane way how:

- we can automate the dependency check
- if CI is green automatically accept the branch and merge the PR

**Comment by bollwyvl** [comment]
> automate the dependency check

```yaml
# conda-forge.yml
bot-inspection:
  update: all
```

This will use the best-available analysis techniques (but mostly `grayskull`) to update the metadata. Sounds great, of course, but It can't handle some of the exotic stuff _this_ feedstock does to accomodate the upstream (dynamic content in `setup.py`, tight pins based on version of python), but _may_ work for simpler feedstocks.

Of note, if the feedstock is capturing `[extras]`, it... won't always get it right.

> if CI is green automatically accept the branch and merge the PR

There is a [bot command](https://conda-forge.org/docs/maintainer/infrastructure/#conda-forge-admin-please-add-bot-automerge) (written on a new issue) that will update the repo accordingly in a PR.

The downside of the above approaches is that the effort for dealing with _broken_ packages (e.g. the bot was wrong) is actually _at least_ two additional issues/PRs:
- one PR to fix the broken version with `build: 1` and the fix
  - as a maintainer, you'd be able to do create and merge this
- one PR to [patch](https://github.com/conda-forge/conda-forge-repodata-patches-feedstock) the released version so that the older one isn't picked by solvers
  - this requires a human review from the volunteer _core_  team who are already fairly strapped for time
- potentially any number of issues to deal with behavior a user that is seeing due to inaccurate update by the bot 
  - but humans make mistakes, too

**Comment by geoHeil** [comment]
thanks!

```
bot:
    # only automerge on successful version PRs, migrations are not automerged
    automerge: 'version'
    # only open PRs if resulting environment is solvable, useful for tightly coupled packages
    check_solvable: true
    inspection: update-all
```

sounds like a sensible configuration
